apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: gpu-booking-webhook-ca-issuer
spec:
  ca:
    secretName: gpu-booking-webhook-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gpu-booking-webhook-tls
spec:
  dnsNames:
    - gpu-booking-mutating-webhook.{{ .Release.Namespace }}.svc
    - gpu-booking-mutating-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: gpu-booking-webhook-ca-issuer
    kind: Issuer
  secretName: gpu-booking-webhook-tls
  duration: 8760h
  renewBefore: 720h
  usages:
    - server auth
    - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gpu-booking-webhook-ca
spec:
  isCA: true
  commonName: "gpu-booking-webhook-ca"
  secretName: gpu-booking-webhook-ca-secret  # The CA certificate will be stored in this secret
  duration: 8760h  # 1 year (Use hours instead of "d")
  renewBefore: 720h  # Renew 30 days before expiration
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: gpu-booking-webhook-selfsigned-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: gpu-booking-webhook-selfsigned-issuer
spec:
  selfSigned: {}  # This issuer creates the self-signed CA

