apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-booking-mutating-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-booking-mutating-webhook
  template:
    metadata:
      labels:
        app: gpu-booking-mutating-webhook
    spec:
      containers:
        - name: webhook
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 443
          env:
            - name: API_TOKEN
              value: {{ .Values.apiToken }}
            - name: API_URL
              value: {{ .Values.apiUrl }}
            - name: GPU_STATS_URL
              value: {{ .Values.gpuStatsUrl }}
          volumeMounts:
            - name: webhook-tls
              mountPath: "/etc/webhook/certs"
              readOnly: true
      volumes:
        - name: webhook-tls
          secret:
            secretName: gpu-booking-webhook-tls