apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-terminator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-terminator
  template:
    metadata:
      labels:
        app: pod-terminator
    spec:
      serviceAccountName: pod-terminator-sa
      containers:
        - name: terminator
          image: {{ .Values.image.pod_terminator.repository }}:{{ .Values.image.pod_terminator.tag }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-terminator-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-terminator-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete","create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-terminator-binding
subjects:
  - kind: ServiceAccount
    name: pod-terminator-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: pod-terminator-role
  apiGroup: rbac.authorization.k8s.io
