apiVersion: v1
kind: Service
metadata:
  name: gpu-booking-mutating-webhook
spec:
  selector:
    app: gpu-booking-mutating-webhook
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: pod-terminator
spec:
  selector:
    app: pod-terminator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080