apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: gpu-booking-webhook
webhooks:
  - name: gpu-booking.k8s.io
    clientConfig:
      service:
        name: gpu-booking-mutating-webhook
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
      caBundle: ""
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore