# Generated by Django 3.2.13 on 2024-10-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maiauser',
            name='minimal_env',
            field=models.BooleanField(default=True, verbose_name='minimal_env'),
        ),
    ]
