# Generated by Django 3.2.13 on 2024-10-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20241017_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='maiauser',
            name='project_admin',
            field=models.BooleanField(default=False, null=True, verbose_name='project_admin'),
        ),
        migrations.AlterField(
            model_name='maiauser',
            name='cpu_limit',
            field=models.TextField(default='2', null=True, verbose_name='memory_limit'),
        ),
        migrations.AlterField(
            model_name='maiauser',
            name='memory_limit',
            field=models.TextField(default='2G', null=True, verbose_name='memory_limit'),
        ),
    ]
