---
- name: Configure UFW rules
  hosts: all
  become: yes
  tasks:
    - name: Enable UFW
      ufw:
        state: enabled

    - name: Allow SSH
      ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Allow all nodes to communicate with all nodes
      ufw:
        rule: allow
        from_ip: "{{ hostvars[item].ansible_default_ipv4.address }}"
        to_ip: "{{ ansible_default_ipv4.address }}"
      with_items: "{{ groups['all'] }}"
