- name: Create volume group using host-specific device list
  hosts: all
  become: true

  tasks:
    - name: Ensure lvm2 is installed
      package:
        name: lvm2
        state: present

    - name: Create volume group "MAIA_Storage" using per-host devices
      community.general.lvg:
        vg: MAIA_Storage
        pvs: "{{ device_list }}"

    - name: Create logical volume 'maia_0_local' in volume group 'MAIA_Storage'
      community.general.lvol:
        vg: MAIA_Storage
        lv: maia_0_local
        size: "{{ local_storage_size | default('100%FREE') }}"
    
    - name: Check filesystem format of /dev/MAIA_Storage/maia_0_local
      command: blkid -o value -s TYPE /dev/MAIA_Storage/maia_0_local
      register: volume_format
      changed_when: false
      failed_when: false

    - name: Show volume format
      debug:
        msg: "Filesystem format is: {{ volume_format.stdout | default('unformatted') }}"
  
    - name: Format volume to ext4 if not formatted
      filesystem:
        fstype: ext4
        dev: /dev/MAIA_Storage/maia_0_local
      when: volume_format.stdout == ""


    - name: Create logical volume 'maia_0' in volume group 'MAIA_Storage' only for nfs_server
      when: "'nfs_server' in group_names"
      community.general.lvol:
        vg: MAIA_Storage
        lv: maia_0
        size: "{{ nfs_storage_size | default('100%FREE') }}"
    
    - name: Check filesystem format of /dev/MAIA_Storage/maia_0
      when: "'nfs_server' in group_names"
      command: blkid -o value -s TYPE /dev/MAIA_Storage/maia_0
      register: nfs_volume_format
      changed_when: false
      failed_when: false  

    - name: Show NFS volume format
      when: "'nfs_server' in group_names"
      debug:
        msg: "NFS volume filesystem format is: {{ nfs_volume_format.stdout | default('unformatted') }}" 

    - name: Format NFS volume to ext4 if not formatted
      when: "'nfs_server' in group_names and nfs_volume_format.stdout == ''"
      filesystem:
        fstype: ext4
        dev: /dev/MAIA_Storage/maia_0
