---
- name: Enable CIFS volume plugin for Kubernetes
  hosts: all
  become: yes
  tasks:
    - name: Install cifs-utils
      apt:
        name: cifs-utils
        state: present
        update_cache: yes

    - name: Install python-is-python3
      apt:
        name: python-is-python3
        state: present
        update_cache: yes

    - name: Ensure directory for CIFS plugin exists
      file:
        path: /var/lib/kubelet/volumeplugins/fstab~cifs
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Download cifs script
      get_url:
        url: https://raw.githubusercontent.com/kthcloud/maia/master/CIFS/cifs
        dest: /var/lib/kubelet/volumeplugins/fstab~cifs/cifs
        mode: '0755'
        owner: root
        group: root

    - name: Download decrypt_string.py script
      get_url:
        url: https://raw.githubusercontent.com/kthcloud/maia/master/CIFS/decrypt_string.py
        dest: /var/lib/kubelet/volumeplugins/fstab~cifs/decrypt_string.py
        mode: '0700'
        owner: root
        group: root

    - name: Copy Private Key
      copy:
        src: "{{ private_key_path }}"
        dest: /var/lib/kubelet/volumeplugins/fstab~cifs/private_key.pem
        mode: '0644'
        owner: root
        group: root

    - name: Run cifs init script
      command: /var/lib/kubelet/volumeplugins/fstab~cifs/cifs init
      register: cifs_init_output

    - name: Output cifs init script stdout
      debug:
        msg: "{{ cifs_init_output.stdout }}"

    - name: Run cifs decrypt_string.py script
      command: /var/lib/kubelet/volumeplugins/fstab~cifs/decrypt_string.py /var/lib/kubelet/volumeplugins/fstab~cifs/private_key.pem 6f00684ed196a05241e319d2131ac574ecf582499d3b191dcd43749f91e781275347cca6fcda03aa91df88ac72660ff5ac0fbd88e3afe08536f30e8944c36cbdc2f81973988c5dd81265c414986c1132527ba246eb963bdd7af29f3e7ce51bd3d5f9d606fc38c346f734734cd43eaaa632111ceae8fc7ca8d1c89bd7081a885a1c1b778208838e0e2323c969de18b39ff2ffb04cf2b9b53f491a1f65f333590a78f7f655bab07c10f06d05bad8c8ae0a4fb1957c1e1020f03b59156f48798efa808bd0aa42ef8cba0c627a50fcd496253ea532b75cff2d94f9a62d03e3935fff9f0fb3027ef5f162a1b6b379bcd108a09c63011f493698cc04f54609cb8c7aa4
      register: decrypt_string_output

    - name: Output decrypt_string.py stdout
      debug:
        msg: "{{ decrypt_string_output.stdout }}"
