---
- name: Run MAIA Core Installation
  hosts: localhost
  vars:
    cluster_config: /path/to/cluster_config.yaml
    config_folder: /path/to/configs_folder
  tasks:
    - name: Execute MAIA_initialize_config with cluster-config and config-folder
      command: >
        MAIA_initialize_config
        --cluster-config {{ cluster_config }}
        --config-folder {{ config_folder }}

    - name: Read cluster config YAML file
      ansible.builtin.slurp:
        src: "{{ cluster_config }}"
      register: cluster_config_content

    - name: Extract cluster_name from cluster config
      set_fact:
        cluster_name: "{{ (cluster_config_content.content | b64decode | from_yaml).cluster_name }}"

    - name: Print cluster_name value
      debug:
        msg: "Cluster Name: {{ cluster_name }}"


    - name: Create namespaces
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ item }}"
      loop:
        - observability
        - traefik
        - metallb-system
        - cert-manager
        - gpu-operator
        - maia-core-toolkit
        - ingress-nginx
        - minio-operator
        - authentication
      environment:
        KUBECONFIG: MAIA-kubeconfig.yaml
        
    - name: RUN MAIA_install_core_toolkit
      command: >
        python3 /home/simben/Documents/GitHub/MAIA/MAIA_scripts/MAIA_install_core_toolkit.py
        --cluster-config {{ config_folder }}/{{ cluster_name }}.yaml
        --config-folder {{ config_folder }}
        --maia-config-file {{ config_folder }}/maia_config.yaml
      environment:
        KUBECONFIG: MAIA-kubeconfig.yaml
      register: maia_install_output

    - name: Print line containing "maia-core-prometheus"
      debug:
        msg: "{{ maia_install_output.stdout | regex_search('.*maia-core-prometheus.*') }}"

    - name: Execute the line containing "maia-core-prometheus"
      command: "{{ maia_install_output.stdout | regex_search('.*maia-core-prometheus.*') }}"
      environment:
        KUBECONFIG: MAIA-kubeconfig.yaml


    
