- name: Install NVIDIA driver using apt
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install NVIDIA driver
      apt:
        name: "{{ nvidia_driver_package | default('nvidia-driver-570') }}"
        state: present

    - name: Reboot to activate driver (optional)
      reboot:
        msg: "Rebooting to load NVIDIA driver"
        reboot_timeout: 600
