---
- name: Print UUID for /dev/MAIA-storage/maia-local
  hosts: all
  become: true
  tasks:
    - name: Get UUID of /dev/MAIA-storage/maia-local
      command: blkid -s UUID -o value /dev/MAIA_Storage/maia_0_local
      register: uuid_output_local

    - name: Print UUID of /dev/MAIA-storage/maia-local
      debug:
        msg: "UUID: {{ uuid_output_local.stdout }}"

    - name: Add entry to /etc/fstab for /dev/MAIA-storage/maia-local if it doesn't exist
      lineinfile:
        path: /etc/fstab
        line: "UUID={{ uuid_output_local.stdout }} /opt/local-path-provisioner ext4 defaults 0 0"
        state: present
        create: yes
        insertafter: EOF

    - name: Get UUID of /dev/MAIA_Storage/maia_0
      command: blkid -s UUID -o value /dev/MAIA_Storage/maia_0
      when: "'nfs_server' in group_names"
      register: uuid_output_nfs

    - name: Print UUID of /dev/MAIA_Storage/maia_0
      when: "'nfs_server' in group_names"
      debug:
        msg: "UUID: {{ uuid_output_nfs.stdout }}"

    - name: Add entry to /etc/fstab for /dev/MAIA_Storage/maia_0 if it doesn't exist
      when: "'nfs_server' in group_names"
      lineinfile:
        path: /etc/fstab
        line: "UUID={{ uuid_output_nfs.stdout }} /nfs ext4 defaults 0 0"
        state: present
        create: yes
        insertafter: EOF
