---
- name: Setup NFS Server
  hosts: nfs_server
  become: yes
  tasks:
    - name: Install NFS packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nfs-kernel-server
        - nfs-common
        - rpcbind

    - name: Create export directory
      file:
        path: /nfs
        state: directory
        owner: nobody
        group: nogroup
        mode: '0777'

    - name: Configure NFS exports
      lineinfile:
        path: /etc/exports
        line: "/nfs *(rw,sync,no_subtree_check,no_root_squash)"

    - name: Restart NFS server
      service:
        name: nfs-kernel-server
        state: restarted

    - name: Enable NFS server
      service:
        name: nfs-kernel-server
        state: started
        enabled: yes

- name: Gather NFS client IP addresses
  hosts: nfs_clients
  gather_facts: yes
  tasks:
    - name: Save NFS client IP addresses
      set_fact:
        nfs_client_ips: "{{ ansible_default_ipv4.address }}"
      run_once: true

    - name: Print NFS client IP addresses
      debug:
        msg: "{{ nfs_client_ips }}"

- name: Gather NFS server IP address
  hosts: nfs_server
  gather_facts: yes
  tasks:
    - name: Save NFS server IP address
      set_fact:
        nfs_server_ip: "{{ ansible_default_ipv4.address }}"
      run_once: true

    - name: Print NFS server IP address
      debug:
        msg: "{{ nfs_server_ip }}"


- name: Allow NFS clients to access NFS server
  hosts: nfs_server
  become: yes
  tasks:
    - name: Allow NFS clients to access NFS server
      ufw:
        rule: allow
        from_ip: "{{ item }}"
        to_port: 2049
      with_items: "{{ groups['nfs_clients'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | list }}"

- name: Setup NFS Client
  hosts: nfs_clients
  become: yes
  tasks:
    - name: Install NFS packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nfs-common
        - rpcbind

    - name: Create NFS mount point
      file:
        path: /nfs
        state: directory
        owner: nobody
        group: nogroup
        mode: '0777'

    - name: Mount NFS share
      mount:
        src: "{{ hostvars[groups['nfs_server'][0]]['ansible_default_ipv4']['address'] }}:/nfs"
        path: /nfs
        fstype: nfs
        opts: rw,sync,vers=4
        state: mounted
