{{- if .Values.dockerRegistrySecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dockerRegistrySecret.dockerRegistrySecretName }}
data:
  .dockerconfigjson: {{ .Values.dockerRegistrySecret.dockerRegistrySecret }}
type: kubernetes.io/dockerconfigjson
{{- end }}