{{- if .Values.cifs.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-writer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-writer-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-writer-binding
subjects:
  - kind: ServiceAccount
    name: secret-writer
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: secret-writer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: cifs-encryption-public-key
data:
  public-key.pem: {{ .Values.cifs.encryption.publicKey }}
{{- end }}