# Default values for maia-namespace.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
pvc:
  pvc_type: "standard"
  access_mode: "ReadWriteOnce"
  size: "1Gi"

namespace: "maia"

users:
- jupyterhub_username: "jovyan"
  sshPort: 3022
- jupyterhub_username: "jovyan2"
  sshPort: 3023

serviceType: "NodePort"

metallbSharedIp: True
metallbIpPool: False
loadBalancerIp: "192.168.0.1"

cifs:
  enabled: False

