{{- if .Values.orthanc_values }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-orthanc
  namespace: {{ .Values.argo_namespace }}
spec:
  project: {{ .Release.Name }}
  source:
    chart: {{ .Values.orthanc_values.chart_name }}
    repoURL: {{.Values.orthanc_values.repo_url}}
    targetRevision: {{ .Values.orthanc_values.chart_version }}
    helm:
      releaseName: {{ .Release.Name }}-orthanc
      valuesObject:
      {{ .Values.orthanc_values | toYaml | nindent 8 }}
  destination:
    server: {{ .Values.destination_server }}
    namespace: {{ .Release.Name }}
{{- end }}