FROM nvcr.io/nvidia/clara/monai-toolkit:3.0 

RUN pip install jupyterhub 



#COPY entrypoint.sh /opt/docker/entrypoint.sh
#RUN chmod 777 /opt/docker/entrypoint.sh
#RUN chmod +x /opt/docker/entrypoint.sh